version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: english_bot_fe
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Seoul
    restart: unless-stopped
    networks:
      - english_bot_network

  # Development service
  web-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: english_bot_fe_dev
    ports:
      - "5173:5173" # Vite의 기본 포트
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - TZ=Asia/Seoul
    command: npm run dev -- --host
    networks:
      - english_bot_network

networks:
  english_bot_network:
    driver: bridge